delete from action_list;
INSERT INTO action_list VALUES(1,'发呆','啊？你刚才说什么？');
INSERT INTO action_list VALUES(2,'上班','努力工作最重要！');
INSERT INTO action_list VALUES(3,'睡觉','.zZ .zZZ .zZZZ .zZZZZ');
INSERT INTO action_list VALUES(4,'穿衣服','今天穿哪件呢？');
INSERT INTO action_list VALUES(5,'刷牙','左刷刷右刷刷');
INSERT INTO action_list VALUES(6,'洗脸','时间再赶也要洗脸');
INSERT INTO action_list VALUES(7,'做早餐','');
INSERT INTO action_list VALUES(8,'吃早餐','');
INSERT INTO action_list VALUES(9,'做午餐','');
INSERT INTO action_list VALUES(10,'吃午餐','');
INSERT INTO action_list VALUES(11,'做晚餐','');
INSERT INTO action_list VALUES(12,'吃晚餐','');
INSERT INTO action_list VALUES(13,'步行','');
INSERT INTO action_list VALUES(14,'骑自行车','');
INSERT INTO action_list VALUES(15,'骑电动车','');
INSERT INTO action_list VALUES(16,'骑摩托车','');
INSERT INTO action_list VALUES(17,'开车','');
INSERT INTO action_list VALUES(18,'开飞机','');
INSERT INTO action_list VALUES(19,'公交','');
INSERT INTO action_list VALUES(20,'地铁','');
INSERT INTO action_list VALUES(21,'打车','');
INSERT INTO action_list VALUES(22,'打船','');
INSERT INTO action_list VALUES(23,'爬行','');
INSERT INTO action_list VALUES(24,'滚行','');
INSERT INTO action_list VALUES(25,'健身','');
INSERT INTO action_list VALUES(26,'玩手机','');

