#ifndef __PROTO_INFO_H__
#define __PROTO_INFO_H__

enum
{
	eSERVER_LOADAVERAGE_BLUE,
	eSERVER_LOADAVERAGE_GREEN,
	eSERVER_LOADAVERAGE_YELLOW,
	eSERVER_LOADAVERAGE_RED,
};

enum
{
	eSERVER_STATUS_STOP,
	eSERVER_STATUS_RUNNING,
};
#define IDKEY_SIZE 32
#define AUTH_MEMBERID_SIZE 32
#define AUTH_STRING_SIZE 4096

#endif
